version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: gcashflow-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
